apiVersion: v2
name: frontend
description: A Helm chart for University Management Platform Frontend (React + Nginx)
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - react
  - nginx
  - frontend
  - university-management
home: https://github.com/your-org/university-management-platform
sources:
  - https://github.com/your-org/university-management-platform
maintainers:
  - name: Your Name
    email: your.email@example.com 