export const dummyData = {
    diplomas: [
        {
            _id: 'dip_001',
            title: 'Advanced Web Development',
            description: 'Learn full-stack web development with React, Node.js, and MongoDB.',
            price: 299.99,
            category: 'Programming',
            thumbnail: 'https://example.com/thumbs/web-dev.jpg',
            duration: '8 weeks',
            prerequisites: ['Basic HTML & CSS', 'JavaScript Fundamentals'],
            status: true,
            createdAt: '2025-01-15T10:00:00Z',
            updatedAt: '2025-03-20T14:30:00Z',
            videoIds: ['V001', 'V002'],
        },
        {
            _id: 'dip_002',
            title: 'Data Science with Python',
            description: 'Master data analysis, machine learning, and visualization using Python.',
            price: 349.99,
            category: 'Data Science',
            thumbnail: 'https://example.com/thumbs/data-science.jpg',
            duration: '10 weeks',
            prerequisites: ['Basic Python Programming', 'Statistics 101'],
            status: true,
            createdAt: '2025-02-01T09:00:00Z',
            updatedAt: '2025-04-10T11:45:00Z',
            videoIds: ['V003'],
        },
        {
            _id: 'dip_003',
            title: 'Digital Marketing Mastery',
            description: 'Explore SEO, social media marketing, and content strategy.',
            price: 199.99,
            category: 'Marketing',
            thumbnail: 'https://example.com/thumbs/marketing.jpg',
            duration: '6 weeks',
            prerequisites: [],
            status: false,
            createdAt: '2024-12-10T12:00:00Z',
            updatedAt: '2025-05-05T16:20:00Z',
            videoIds: [],
        },
        {
            _id: 'dip_004',
            title: 'UI/UX Design Fundamentals',
            description: 'Design user-friendly interfaces with Figma and Adobe XD.',
            price: 249.99,
            category: 'Design',
            thumbnail: 'https://example.com/thumbs/uiux.jpg',
            duration: '7 weeks',
            prerequisites: ['Graphic Design Basics'],
            status: true,
            createdAt: '2025-03-01T08:30:00Z',
            updatedAt: '2025-06-01T13:15:00Z',
            videoIds: [],
        },
    ],
    videos: [
        {
            _id: 'V001',
            title: 'Introduction to React',
            duration: '25:30',
            uploadedAt: '2025-01-20T10:00:00Z',
            module: 1,
            status: 'Published' as const,
            diplomaId: 'dip_001',
            description: 'Basic concepts of React components and JSX',
        },
        {
            _id: 'V002',
            title: 'Node.js Fundamentals',
            duration: '18:45',
            uploadedAt: '2025-01-25T12:00:00Z',
            module: 2,
            status: 'Draft' as const,
            diplomaId: 'dip_001',
            description: 'Setting up a Node.js server',
        },
        {
            _id: 'V003',
            title: 'Python for Data Analysis',
            duration: '32:15',
            uploadedAt: '2025-02-10T09:00:00Z',
            module: 1,
            status: 'Published' as const,
            diplomaId: 'dip_002',
            description: 'Using pandas and numpy for data manipulation',
        },
    ],
    enrollments: [
        {
            _id: 'enr_001',
            studentName: 'Alice Johnson',
            studentEmail: 'alice.johnson@example.com',
            courseTitle: 'Advanced Web Development',
            enrollmentDate: '2025-02-01T10:00:00Z',
            status: 'Approved' as const,
            progress: 75,
        },
        {
            _id: 'enr_002',
            studentName: 'Bob Smith',
            studentEmail: 'bob.smith@example.com',
            courseTitle: 'Advanced Web Development',
            enrollmentDate: '2025-02-15T12:00:00Z',
            status: 'Approved' as const,
            progress: 40,
        },
        {
            _id: 'enr_003',
            studentName: 'Charlie Brown',
            studentEmail: 'charlie.brown@example.com',
            courseTitle: 'Data Science with Python',
            enrollmentDate: '2025-03-01T09:30:00Z',
            status: 'Approved' as const,
            progress: 90,
        },
        {
            _id: 'enr_004',
            studentName: 'Diana Prince',
            studentEmail: 'diana.prince@example.com',
            courseTitle: 'Digital Marketing Mastery',
            enrollmentDate: '2025-04-10T11:00:00Z',
            status: 'Pending' as const,
            progress: 0,
        },
        {
            _id: 'enr_005',
            studentName: 'Evan Wright',
            studentEmail: 'evan.wright@example.com',
            courseTitle: 'UI/UX Design Fundamentals',
            enrollmentDate: '2025-05-01T14:00:00Z',
            status: 'Rejected' as const,
            progress: 0,
        },
    ],
};