export enum FinancialErrorType {
    MissingRequiredFields = "All required fields must be provided!",
    InvalidStudentId = "Invalid student ID!",
    InvalidChargeId = "Invalid charge ID!",
    InvalidPaymentId = "Invalid payment ID!",
    InvalidApplicationId = "Invalid application ID!",
    InvalidScholarshipId = "Invalid scholarship ID!",
    InvalidId = "Invalid ID!",
    InvalidAmount = "Amount must be greater than zero!",
    InvalidStatus = "Invalid status!",
    InvalidDueDate = "Invalid due date!",
    InvalidPaymentSignature = "Invalid payment signature!",
    PaymentNotFound = "Payment not found!",
    ReceiptNotFound = "No receipt available for this payment!",
    ApplicationNotFound = "Application not found!",
    ScholarshipNotFound = "Scholarship not found!",
    ScholarshipClosed = "Scholarship application is closed!",
    MissingDocuments = "At least one document is required!",
    UserNotAuthenticated = "User authentication required!",
    UnauthorizedAccess = "Unauthorized access!",
    FileRequired = "File is required!",
  }